/************************************************************************/
/*@File Name         : 求字符串中好分割的数量.cpp
/*@Created Date      : 2020/8/8 8:42
/*@Author            : ccpang(ccpang96@163.com)
/*@blog              : www.cnblogs.com/ccpang
/*@Description       :给你一个字符串 s ，一个分割被称为 「好分割」 当它满足：将 s 分割成 2 个字符串 p 和 q ，
它们连接起来等于 s 且 p 和 q 中不同字符的数目相同。请你返回 s 中好分割的数目。
//维护两个数组表示左右两边的数量
/************************************************************************/



#include<iostream>
#include<string>
using namespace std;

int numSplits(string s) {
	
	if (s.size() <= 1)
		return 0;

	int left_hash[26] = {0};
	int right_hash[26] = {0};

	//初始化
	int left = 0;
	for (int i = 0; i < s.size(); i++) { //O(n)的时间复杂度
		int c = s[i] - 'a';
		if (left_hash[c] == 0)
			left++;
		left_hash[s[i] - 'a'] ++;
	}

	cout << left << endl;

	int res = 0;
	int right = 0;
	for (int i = s.size()-1; i> 0; i--) {

		int c = s[i] - 'a';
		if (right_hash[c] == 0)  //right_hash有新的字符种类出现
			right++;
		right_hash[c]++;

		left_hash[s[i] - 'a']--;
		if (left_hash[c] == 0) //说明left要减为0
			left--;
		if (left == right)
			res++;
	}
	return res;

}



/*
int main() {
	
	string input = "dddabadacbdbbabbaeccaedceaedacceebdedadacbeeceacedbcbccdcdadcdeeaadaeadcbacbaacacadcabbcaabebcecdaebecbdbcdbbebaaaacaacdbdcbaabccdeedceeedeaacbecccadaadacaaccbdaaaeaeceaeecdeddeccdeadeadddbadbbbacdbdcbcaeaaacecaadacddcadebeddacccecaccedeabacbabdbaacddcbbbdeecadebdebcaecbcbdeedbdaceebcacbcaaebbdecaeadeadeeccedcbcebaeabbbbeaeaaaeeedabcdaecceddeccdbcdddcbccadaaaddcdcbddbeaadcdadedeeccadbaecbcbebcceadaabcdcadabbcbbbcbaeadacbabdadbddbedcecebbccbcbcabcdcbecaaaaededaedbdebadaebacaeabbebbbaccbacedccbbbecbbbadbaebabbcbeaccbceecbeeaacbbbddcccccadedecceadccddccdbcdebaaeabeeeccaebcbecdeecbddeeacecaacccebdcddeaebabbeaaaaceaeeecbabedacbacaccdbbccddebaaecbaddeacecdabdabaecaadecbcdbbeecccbdcbbaaaaadaaeddaebeacdaadaeaaeaceadbbbedaeecaceaebbeeddebbacbcbabdcebdbcebcbedbebeaacebacdbaedbaeeadacccaadadcacaecaebbbbecddbcacdcadcbdaaaadebcdedcdaeddecaaedccaaabbbeabdbedbccdcbecbbdbddbabdadbeedeaeeaeccdeaadeebeececaedebdbdedbabbcabecebdedeeabebabbebaebbdaeaedcbeebacaccdcdcecedceccabebdddbddcabcdbccbbdadebcdaadeacbacceacdadacdceecceebdcbeccebcaebdbdcebaecbdccdaecaaecdabcbddeccdcbccbecacceccbdbcabbacaaecdaeccedacbbcddadacbecbcecdcdacdbbcbbdcbddadcbabadbdbbbaaabcedadaedcddadaadcaeebcacdbebecbbacbbccaeaebcabcdedbabbbbdeeecbbaabcaddaebbedaadeacacdbbaabaaaeedadeaebeaddaaddadebdadabdbdaacddceeabddbcdecaaebaadbcacaddadbeeabdacdaeadacacbddcabeaebaadebcceacdeeaddcbaeecacabcbceddccececebebbbadeececadcceeeebddeeecadadbaadebcccebacccabbcceadaaaedeaebeecbadbeccecdbbbdeaccdddbeaddbabeebcddabcccdaabdabcdbbcbaadecccadbaecdcbbbecbdeddacabcadaebadeddbbdcaabbeaebcacbeabcbebbacddeadaeaceaabbdbebaccbadddddceaddbbeadbeaecebadadaadaddbedabdcbcaedbcedecccdaddbaacdacebaadeaaeabcbccccadbeaaebaecbabdeadcebeaadbdccabecaabceecabeedbcccedcdeeeeeccdedbeebabbeccbcadedceaedaceddacabaadbcaaeaccaadaddcaebaaebedceaabbcbcebbbcccddcabeacdaebacdbebcececbbadaeeeacaadedaacaceedbabcedcadcaaadeccaadcaecebcdbdaeacedcacbdedaeddaacdbaabebcccabaddebeaaceaaccabaecbbccddabeabadedbdadcbdeeddebdadccadbaaadccadecbedeadddcdcaebaaacdecbedcbeeebeabddacdcdedcceabaedecdccaeeebdacccabebbaaeeeaaccbccbecdeaabeeccceddcbabedcaaacbdebeeeadaceabdcddeaaaddddddeebaedecdbcedaadbbdbeedceaabcdbdbeaadeebbedbaacdbbcdebbedcdcebdaacbccedeebacbaaaecebddddabcecbeddadebaddecebccebaaececeddccbbdeecbacdcbcdcecbadbecaaeeccececbeddbebcaaddccbacacdaeaedcbadadbdbedebacdeddbadaeebeccbecbdebbddecddcaaacbddbbaddaaeeedeeddedbadcbddacbccdaeedaeeabcbabeedecbcbeaadeaaedeacbaaaecddcecbceeeddedddedbbeebcbececdacbceaaeabbaaddcbeaecacacbbccdaecbbabdcbdbdadebcbaeecebedaacebcbccabcabbbaedeaecddbbcdbbdebebbdaddcdbdcebdbcbdaabaaccbeadbdbbeaadccccbbccdebadbdaadabcbecddebecdbceecabceaddacdccceedddeabcdbcbbdaacbcceeebbcbbacbbcdaebbcebdaebbbaaececdcddcaaadeccceabdbdeacdcddcdaaacaedbcdeecebeeeecceccbddbdacdceaddabccbaccabacdcbcadccaeaaaaaecdecddabeaddbbdbdeddadacebeaddbeaddcadccccababcedcaebedbadebeaacdbcbcbdaadeaecdddacdaaeedddbdaddbebccdceecaaddddaadcabdeccdaccaacbdcaeaccaabcbbadccdeceedaedbacdeaecdeeeabadaabebdadceddccdcabebddcaabdebccdeedaaaecdadbaeebecebaadcccabebcaecbdbabbdddcbecacbdacdacadbebbabdbbbddabbbbdcdedaddbdbabdbaebeebaadeeaccadeaeaedcaeacdcacbeabededbedabaeddedadbbeeaaaaadbdaedaadecebceccbbedddecabdbaebddeaeeecdcedeacddddbeedeeaacbdbceedaaebbbeabaeddacddbbbeeddabbbeeedeedadceaecbeadacaacbebddeaacbaadeceeecaeedaaaebbbecdbaaeceebcbbdcbdaddceceebcaaddcbbdbaadcbdadaddababdaaaebbaaabedacdbcaccecbeaceebbaedcccbdccebcaddbcaaedbadeadbccaedacbeecddcccebcdbcbaaaabcedbcdcecbdcbbebadaeeaeacdbaadecdcbceacbcdcaaaabcacaecbaeeaaacabeedaebceabeaaebdebccabaababbcbbeabacaeceaebcddcdbceeedcdcedbbcbeddabdddaceddcedecdeaddbeaacdeaeeedcbdeddedccabadecbdbeaeceadbaddbbdbebbabdaeacdaaeeceaadaeaceccecdadeabbddcceaceeeacdcdddddecaebccdabcbaebbdbdcdebebcabbdeddddaacadacbdeecdebcedeccebbbabdaddbecacaeceaaedbedcdacddaebccbdceacebccabaaeaaadceaeddcdecdbbaeaabdbeabbbbdbbeededdaeaabeeacdaecdabaebedbbabbdacaccbbdecebcebcaebbcbdadeaabecdcbddecdabaacbddbdbcbcdacccdadddcdadbeecabbcdddbcecdcdcadeceacdeeaebcedeeaceaaddcbeeaeeeeaeeceeaccbcbcaeadddaadcebbdbdccacebddeccdbebdbaadacbbcacdebebcdacacdcdedabceaedbcaedecebbdbdededbaeaaaeedbedbcddeeddddbcdaeeabbadabadaabdbcdbbdabbbebaeecbedbaeceaccdecbacbedceecbbbdcaceadacacebbbddbeeaacaaeabdecadceaacaeaaeeddeadbbcacdeebcaccdbbbeebdcdeacabcdcebeaeecacedbcbdcedcbbabadcebaabdacbeddcbacedabbcbebbeebaebaccbadcdbacdcaeadedceabdcecbebdaaceeabcaaabeddcceeddcaccbaebceeebbadcedacdcdbcbabeddebecadaaccbcacbadccdeaceecbccbbbccceaadcaaabbeecadaebadaabbdbeabdaeeecbececbcdecaaedacdbeacececdbacddadcbceeabbeeeaccabbcccdbdaedbbedeaeaddeddecccecabdacedeabdaebebedecaeaccadbdebdeacdadedebececcbdedcecbecacacbeadebdedcddeedddbcdbcaedbeecddaccabbaaaecbbdedaadbbdadaddaeeeaeabdaadcbaedebcdcacbbcdecaabaedceebabcdebdbeebaeecdcbabcaceadbdaaebcadeabdbeccececcbcbccddacaaaddedbbbdecacceddedcbcceceddebbbadeeaaadabeddaaccdbebdeabebcbbeabceededebcbceebbeebddbdecebeebcaebcabddeacaeeadccedbcebabddadedbeeadacdccaaecbedbbccaeadebdbaeccbcebddeeaadbbcccaedaeeeeadbeebbdbddccbbadbabccccedebbbbabcdabeebdcbccccbedceddeecbaedddacccedeabdbdbdeeadacddcebdddbcecbebeeaccdbcbeeaecaacbdabcceeaecdceacbeddecdeddecabaeaaeddcaecacbddbacbdeabdeaabdedccedeacddadaaaecabdeccedaaecaccdedcdbbceccbbabaacbcbbddecbcccbacbcddeaaadcadecbcaaeeeabaeecaebdacaabedceddacbeabdcacebbadedeadadbbeadceceeaebeeaeadddaacaadeaacdedcaccbaececaedaababdebeabebbbcdddbcebdcbcaebbbecacdbebdaadbbadeaeccaacbababaaaeebacedaeabcccdeacaaaadcbeebdececdaeabeeaedcbacbedcdcaabdadcdbeeceebcdcdeddcacacbaddedabcabaddabeedcdeddadaaeccbcabbcdabecdadccacabccedaadedcbdaeacacdeabcdccebeacdedeeaeeaaeddceceeceaaabdaabacbcbcbcdbcbeaaeaddaccbecdaabcbddbabeddbecedbeaeadeedbbdbbaecbbbbcbedcbbaabacdbceedaabdcecaacdeadbaeccddcdcbbccdbcbdeeecceddaddbcdeadceeeecaceabaddedcaaeebdacccdbdbbdaeadcacbecaeaeaaddadabbdebdeaccdbbbaddcceaeebabdceebdaacadaaacdebbeeadababdddedddabbbcbecccdbbacbbeebcadbcadebbeaabeebbbabbaeecbabbebeebcddebbecbceccabedaebdaebabceebdeebdcbdddddddeeadbebdacbddbaeadbedbceeedcaacaeeeaaadebbaeeeeaabadcbeacaceeacaecdcdeaacbbaceeedaadddebacbedcaebaeddacabaededebcdcecacaacaedbedcccaeddbacbadedbeaddbccabcddebeaecaadebbbdcbcaddeebdcceebecbaebcaeadbceedcbdbebadceaeeabbbdcaecaaecdcceeddceeeacbebcdeaabddcdcecdbdebabdbcaaecbceecdecbbdebdecbeaaeccebddbdcbbbebedecbbcaaeeddcbbebeededecbaebeadabbadedbaabddcedadaebddbcdadcaaedbddebbbdacddebbcbccdadbaaaebbbcebbdbbecaeadedbaeadbddcceedbbdaceedbdebdabccebbcdeedeecccabebbdedaedbbdbbaaabaceeeeeeddcebacbcaddcdceedabcbcddccbabdaccaaecedecccaecacedeeedabaadbadbdcbbbaaecaccabbcadabbaeabdeebeaabdedebceaacbbadddbacceabeeaceeddeedaaddaeeaeccbbeaeddbacbebdbbccdceeabcedabdebadbbccddadbbbcbcebaaeabcdeecbcdbcbcbeebbcdebeecdcdcceaeddebbcebeebddaadadbddacacacadcacdcabececacaecaaabdbbaadbbedcdcadbbddabbcccebceddceedaeadaaebcbcecedeadcccaeadaeacdcdaaacdcebebcdacbcaddcdceccbabdebababbeabacccdbaacabdacccdbbeecceaceceaeadbddacbceacebbaaaacbeedddeecbaebcabbcebaebaebbcdbedabaaeaacdedadcbacdccdeebcdabcadeababbeaebebacacdbedbcdadcedccdebbcbbeaaeceedcccdeccdbdaacbedbbcceeedbeebdadbbacadeeecdcdaecccbbdaedbdddacecedacbcedbceeacabcceecacadaadddbddbccedabcaeeeaebaecadcdaaedacceeaaaceabacecadeacadbbcecdbaabdcdaeccdabbdccccadebdceeebeeaaabddddaadecebceedecabdccabcbdeceaceceebbdbbeebbcaceeabddadeeeccaabeeebeddeeccdeceaceceacdedcedaacbddaaecaccbecaeabceaeadccbeeeeeeaedbbaeecaacecadccaeeacaaebcdccebdcaebbeaccbddaaabdbdcdbabccecebdcecbbbcbacbddbdddececcdddaccddacdaebaadbeaaaaebaaaedbcbccaddaecaaeccabbabcbedbeaecbccccbdcecdadabbcdddddeecadaacccbaebddeeeaabbcbccccbbbdebbabebcdacdcaaeccedabeeaaacbeacbebeccaabdbebebdebbadbeceeedcdcdbdecacabdebedccdeebadacccddabccceddcccedbedecaacbbbbddbdbbcdacbeaadcceccbbbaaccacbbadecdcddaaeedceddacbaaaedddbedebdbadccbebbdbcaadddbeaadcaaebdcaeadaacaaaaaabddcbbaddaebcebcbbacbeeadbaadeebdeaebbcecdaaaeacaabbaddabacdcceabecaaabbebeacbacadaeedcedaeebecaceecbabccedcdedbecdceabddacedddcbcbbbaebddeecbcecdcaddadadcadeedccdbbadeccecdedcbdcdebcdadadabbebdebecbbcbebdebdddaaedcabceaecdaadedddadacabaaaebdaeddbbdadabadadcaaadccddcdcedaadeeabaacdbdcdccadcaadceddedbcbaddcebebdbccacceddeaadccabadceceeabdaccecdeebadcbcccdddaceebbeadcbecbbdecbeeeebbacedbbadaceeadbbadeecaadedeaeaccbbbcccacadcbaeebdbbeddbacaecabcbdaebdcdbadeaacbcbebebebbdceaadeaedaabedebeeaaebcddcaebeeadbedeadcaedbcbbcddcbabdecdedbedbbaebaabbcbedbbbdeceecedecbacdaebcbaaaebedaaabaccaebbcbeaaeeaabbbeedbddcccaedecbacacceedbeeaeadccacebacdeabbdbebccaaeadecccbcebababdbbdaececeedacbdcaeaadbeceddedcecabedacedddedcabdbaebdccaaaadeadededbeeebabeddacdeedcedecdddbbebebeadcaeacbdecdedcbeebaccccdbaaddbdeceabcaaedeacbeaebccbeaaecdccaddeddaaeccbccbcbebeacbbddbedddbdceddcbbbbcbbbbdaabcbbdedadaceeebaaedbedebadbebbaecbcdddaacdeebdeceacaaabececaaceedadaaaedccecabdceedbbcbeceacebcedaddcbddccadabccddcabccccceacdddebbbcabeebaacddebdbcecabbbbcbbadecaecaecedacebecbeaeadbbdeeddbcbebbdcaebadccabcaebbaceadeeaecbdecebdcbdcbcaacbddcaacdecbdbebdbceabdaebeedecbccebabeeeddeeccdebccacbaaabddcdadabacdeeedaadcbdaabbeaaebcacbbcdaaedabdcedbacdabbddcadbddcedeebabdccaeaddabcdebbeaacedcebbcdcaaeebcbaccaacbdbacceecdaeebcdbadccadbeddbdedddacebabcecbeeeeedcdaaaecdbbecddeddedcdabaebbceabceeedbcacadddadceecbcdaccaddecacacccdddeacbebbdaeadcadeddbceddadcaeabaebaccbaeedbeccadbebacadbeecbbdaabdbdbdbbdcbaedeaeedebaaddecbeddbbacaeaecdaecaebcdbccccaeacbaaedbecacadedcbeeaddececdebdbbbabebaacdebdbeeebacddedbcdccbdcacadebaabcccccaeccdbdeededadadbdbedaccbcedeeceacbcddddaaeabdcdcebceabeceecaabcbdeebbbabccbdcbaaededbbbdccdcabcddeedbcbbbaaacaceccdadedbecbbacebecdacaebbecdabadbccbacaecdbabcaaccdcacabadbcdbaeedbcedbdbbcdaaabcdcceabeacedddbbbbeecdaddcebccabbdcdaebeeadaaecdcbcddbddaabdbbcbedbbaaadaddbbbeddaeccdeaadeacebbdecdadbccceeacedddaeaadbdcaaeacabdacbdeacbcaeeaeeaaaadebbcbaabebdecaebcbeabddcdddcdbeeedcadcbebeeeedcccdcccebceadcdbacdebedcbdbbcbeebcaaeecbdcccbedcdcabaeecabcdabceeaeaddeddcbddbdceeaddaceeeaddcbcedbaecbbdccaaabaadeecaebbbbcebbdaabacdea";
	int result = numSplits(input);
	printf("%d", result);
	system("pause");
	return 0;
}
*/